---
language: ruby
bundler_args: --without development
script:
  - bundle exec rake test
before_install: rm -f Gemfile.lock
before_script:
  - npm install
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
  - rvm: 2.0.0
  - rvm: 2.1.0
notifications:
  email: false
