---
language: ruby
bundler_args: --without development
script:
  - bundle exec rake test
before_install: rm -f Gemfile.lock
before_script:
  - npm install
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  - PUPPET_HERALD_ENV=production
  - PUPPET_HERALD_ENV=development
notifications:
  email: false
